language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

script: phpunit

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.3
  include:
    - stage: test
      php: 7.2

    - stage: test
      php: 7.3

before_deploy: composer build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 'dist/release-flow.phar'
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - hoogi20@googlemail.com

