language: php

php:
  - 7.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git-flow

before_script:
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install

script: phpunit

notifications:
  email:
    - hoogi20@googlemail.com

